version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ./backend/.env
    networks:
      - eva-tec-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - eva-tec-network

networks:
  eva-tec-network:
    driver: bridge
